services:
  postgres:
    image: postgres:16
    container_name: whodis-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whodis
    ports:
      - "5432:5432"
    volumes:
      - whodis-postgres-data:/var/lib/postgresql/data

volumes:
  whodis-postgres-data:
