import { QuestionItem, QuestionModule } from "./types";

const option = (
  id: "A" | "B" | "C" | "D",
  text: string,
  tags: string[],
  nextHints: QuestionModule[],
) => ({ id, text, tags, nextHints });

export const questionBank: QuestionItem[] = [
  {
    id: "personality_structure_early_01",
    module: "personality_structure",
    stage: "early",
    question: "你觉得自己平时更接近哪一种人？",
    options: [
      option("A", "想得比较多，做决定前会反复权衡", ["overthinking", "cautious_decision", "risk_aware"], ["behavior_action", "inner_loop"]),
      option("B", "感受比较敏锐，很容易察觉细节和氛围", ["sensitive", "observant", "emotion_aware"], ["relationship_pattern", "pressure_defense"]),
      option("C", "表面看起来还好，但很多事习惯自己消化", ["self_contained", "hidden_pressure", "low_expression"], ["relationship_pattern", "pressure_defense"]),
      option("D", "目标感比较强，不太能接受自己原地踏步", ["growth_oriented", "self_demanding", "achievement_need"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "personality_structure_early_02",
    module: "personality_structure",
    stage: "early",
    question: "面对一个不熟悉的新环境，你通常会先怎么进入状态？",
    options: [
      option("A", "先观察规则和人际氛围，再决定怎么参与", ["observant", "cautious_entry", "context_reader"], ["relationship_pattern", "behavior_action"]),
      option("B", "会尽快找到自己能掌控的一小块事情", ["control_need", "practical_anchor", "stability_seeking"], ["core_base", "behavior_action"]),
      option("C", "如果没有必要，会先保持安静和低存在感", ["low_expression", "self_protective", "reserved"], ["pressure_defense", "relationship_pattern"]),
      option("D", "更愿意主动试探边界，看看哪里能发挥", ["initiative", "growth_oriented", "exploratory"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "personality_structure_middle_03",
    module: "personality_structure",
    stage: "middle",
    question: "你更常被哪类评价触动？",
    options: [
      option("A", "别人说我想太多，但我觉得那是必要准备", ["overthinking", "need_for_clarity", "risk_aware"], ["inner_loop", "pressure_defense"]),
      option("B", "别人说我太敏感，可我确实能感到细微变化", ["sensitive", "emotion_aware", "detail_attuned"], ["relationship_pattern", "deep_needs"]),
      option("C", "别人觉得我很稳，但不太知道我内部消耗很大", ["hidden_pressure", "self_contained", "stable_surface"], ["inner_loop", "pressure_defense"]),
      option("D", "别人觉得我要求高，但我只是很难接受含糊过去", ["self_demanding", "high_standard", "clarity_need"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "personality_structure_middle_04",
    module: "personality_structure",
    stage: "middle",
    question: "当你需要表达真实想法时，最常出现的顾虑是什么？",
    options: [
      option("A", "担心信息不完整，表达之后被误解", ["precision_need", "fear_misread", "cautious_expression"], ["relationship_pattern", "inner_loop"]),
      option("B", "担心自己的情绪影响别人判断", ["emotion_control", "considerate", "self_contained"], ["relationship_pattern", "pressure_defense"]),
      option("C", "担心暴露太多会失去安全感", ["boundary_need", "self_protective", "privacy_need"], ["deep_needs", "pressure_defense"]),
      option("D", "担心说出来之后必须立刻承担后续行动", ["responsibility_aware", "action_pressure", "risk_aware"], ["behavior_action", "inner_loop"]),
    ],
  },
  {
    id: "personality_structure_deep_05",
    module: "personality_structure",
    stage: "deep",
    question: "你对自己的要求通常来自哪里？",
    options: [
      option("A", "来自内部标准，不太需要别人提醒", ["internal_standard", "self_demanding", "autonomous"], ["core_base", "inner_loop"]),
      option("B", "来自对失控和出错的提前预判", ["risk_aware", "control_need", "preventive"], ["pressure_defense", "behavior_action"]),
      option("C", "来自不想让重要的人失望", ["responsibility_aware", "relationship_sensitive", "approval_concern"], ["relationship_pattern", "deep_needs"]),
      option("D", "来自一种必须持续进步的紧迫感", ["growth_oriented", "achievement_need", "future_driven"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "personality_structure_closing_06",
    module: "personality_structure",
    stage: "closing",
    question: "如果只能保留一种自我描述，你会更认同哪一句？",
    options: [
      option("A", "我需要理解清楚，才会真正安心行动", ["need_for_clarity", "cautious_decision", "stability_seeking"], ["core_base", "behavior_action"]),
      option("B", "我能感到很多东西，但不一定都会说出来", ["sensitive", "low_expression", "emotion_aware"], ["relationship_pattern", "deep_needs"]),
      option("C", "我习惯自己扛住，再慢慢整理", ["self_contained", "hidden_pressure", "resilient"], ["pressure_defense", "inner_loop"]),
      option("D", "我很难停在原地，哪怕外表看起来平静", ["growth_oriented", "self_demanding", "achievement_need"], ["behavior_action", "inner_loop"]),
    ],
  },
  {
    id: "behavior_action_early_01",
    module: "behavior_action",
    stage: "early",
    question: "遇到一个新任务时，你通常会先做什么？",
    options: [
      option("A", "先拆解目标和风险，再开始行动", ["planning_first", "risk_aware", "structured_action"], ["personality_structure", "inner_loop"]),
      option("B", "先试一小步，边做边调整方向", ["iterative_action", "adaptive", "low_entry_barrier"], ["core_base", "pressure_defense"]),
      option("C", "先确认别人期待什么，避免误解", ["expectation_check", "relationship_sensitive", "precision_need"], ["relationship_pattern", "personality_structure"]),
      option("D", "先找最关键的问题，快速推进核心部分", ["priority_focus", "decisive", "achievement_need"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "behavior_action_early_02",
    module: "behavior_action",
    stage: "early",
    question: "你什么时候最容易开始拖延？",
    options: [
      option("A", "信息不够完整，不确定怎么做才稳", ["uncertainty_block", "need_for_clarity", "overthinking"], ["inner_loop", "core_base"]),
      option("B", "任务太大，看不到第一步", ["activation_difficulty", "needs_decomposition", "overwhelmed"], ["inner_loop", "pressure_defense"]),
      option("C", "别人期待含糊，我怕做偏", ["expectation_check", "fear_misread", "relationship_sensitive"], ["relationship_pattern", "inner_loop"]),
      option("D", "我知道该做，但状态没有到位", ["state_dependent", "energy_sensitive", "self_pressure"], ["pressure_defense", "deep_needs"]),
    ],
  },
  {
    id: "behavior_action_middle_03",
    module: "behavior_action",
    stage: "middle",
    question: "当你真正进入状态后，行动方式更像哪一种？",
    options: [
      option("A", "高度专注，不太想被打断", ["deep_focus", "low_interrupt_tolerance", "structured_action"], ["pressure_defense", "deep_needs"]),
      option("B", "不断优化细节，直到自己满意", ["high_standard", "detail_attuned", "self_demanding"], ["inner_loop", "core_base"]),
      option("C", "会同步照顾结果和他人的感受", ["considerate", "relationship_sensitive", "responsibility_aware"], ["relationship_pattern", "pressure_defense"]),
      option("D", "先把核心结果做出来，再补边角", ["priority_focus", "pragmatic", "decisive"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "behavior_action_deep_04",
    module: "behavior_action",
    stage: "deep",
    question: "你对“行动起来”最需要哪种支持？",
    options: [
      option("A", "帮我把现实问题、情绪问题和行动问题分开", ["needs_problem_framing", "clarity_need", "action_support"], ["inner_loop", "core_base"]),
      option("B", "给我一个很小但具体的下一步", ["needs_next_step", "activation_difficulty", "practical_anchor"], ["deep_needs", "pressure_defense"]),
      option("C", "先确认目标是否值得，不要急着催我", ["value_check", "autonomy_need", "low_pressure_support"], ["core_base", "deep_needs"]),
      option("D", "提醒我停止过度打磨，先交付一个版本", ["perfectionism", "time_boundary_need", "self_demanding"], ["inner_loop", "pressure_defense"]),
    ],
  },
  {
    id: "behavior_action_closing_05",
    module: "behavior_action",
    stage: "closing",
    question: "你更适合哪种行动节奏？",
    options: [
      option("A", "先规划，再集中推进", ["planning_first", "deep_focus", "structured_action"], ["core_base", "pressure_defense"]),
      option("B", "先启动，再快速校准", ["iterative_action", "adaptive", "pragmatic"], ["core_base", "deep_needs"]),
      option("C", "先确认边界，再稳定执行", ["boundary_need", "expectation_check", "stability_seeking"], ["relationship_pattern", "deep_needs"]),
      option("D", "先抓重点，再持续优化", ["priority_focus", "high_standard", "growth_oriented"], ["inner_loop", "core_base"]),
    ],
  },
  {
    id: "relationship_pattern_early_01",
    module: "relationship_pattern",
    stage: "early",
    question: "在人际关系里，你最看重什么？",
    options: [
      option("A", "边界清晰，彼此都不用猜", ["boundary_need", "clarity_need", "low_guessing"], ["deep_needs", "pressure_defense"]),
      option("B", "情绪被理解，而不是被评价", ["emotion_aware", "validation_need", "sensitive"], ["deep_needs", "pressure_defense"]),
      option("C", "长期可靠，关键时刻能承担", ["reliability_need", "responsibility_aware", "trust_slow"], ["core_base", "relationship_pattern"]),
      option("D", "沟通高效，不制造额外消耗", ["efficient_communication", "low_drain", "precision_need"], ["behavior_action", "inner_loop"]),
    ],
  },
  {
    id: "relationship_pattern_middle_02",
    module: "relationship_pattern",
    stage: "middle",
    question: "当别人靠近你时，你通常会怎么建立信任？",
    options: [
      option("A", "先看对方是否稳定一致", ["trust_slow", "stability_seeking", "observant"], ["core_base", "deep_needs"]),
      option("B", "先看对方能不能尊重边界", ["boundary_need", "self_protective", "autonomy_need"], ["pressure_defense", "deep_needs"]),
      option("C", "先看沟通是否真实而不压迫", ["authenticity_need", "low_pressure_support", "sensitive"], ["deep_needs", "pressure_defense"]),
      option("D", "先看彼此能否共同解决问题", ["problem_solving_bond", "pragmatic", "responsibility_aware"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "relationship_pattern_middle_03",
    module: "relationship_pattern",
    stage: "middle",
    question: "关系出现摩擦时，你更常怎么处理？",
    options: [
      option("A", "先自己消化，等想清楚再说", ["self_contained", "delayed_expression", "overthinking"], ["inner_loop", "pressure_defense"]),
      option("B", "会捕捉对方情绪，但不一定马上指出", ["emotion_aware", "observant", "cautious_expression"], ["pressure_defense", "deep_needs"]),
      option("C", "倾向于把事实和责任边界讲清楚", ["boundary_need", "precision_need", "responsibility_aware"], ["behavior_action", "core_base"]),
      option("D", "如果消耗太大，会直接拉开距离", ["withdrawal", "self_protective", "low_drain"], ["pressure_defense", "deep_needs"]),
    ],
  },
  {
    id: "relationship_pattern_deep_04",
    module: "relationship_pattern",
    stage: "deep",
    question: "你最不适应哪种沟通方式？",
    options: [
      option("A", "模糊暗示，让我一直猜", ["low_guessing", "clarity_need", "energy_sensitive"], ["inner_loop", "deep_needs"]),
      option("B", "用情绪压迫我立刻回应", ["low_pressure_support", "self_protective", "emotion_control"], ["pressure_defense", "deep_needs"]),
      option("C", "轻易否定我的复杂感受", ["validation_need", "sensitive", "fear_misread"], ["deep_needs", "pressure_defense"]),
      option("D", "只给态度不给解决路径", ["needs_next_step", "pragmatic", "efficient_communication"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "relationship_pattern_closing_05",
    module: "relationship_pattern",
    stage: "closing",
    question: "在稳定关系里，你更像哪一种角色？",
    options: [
      option("A", "可靠的整理者，把混乱变清楚", ["reliability_need", "clarity_need", "structured_action"], ["core_base", "behavior_action"]),
      option("B", "敏锐的感知者，能提前察觉变化", ["sensitive", "observant", "emotion_aware"], ["pressure_defense", "deep_needs"]),
      option("C", "安静的承担者，不轻易把压力外放", ["self_contained", "responsibility_aware", "hidden_pressure"], ["inner_loop", "pressure_defense"]),
      option("D", "共同成长的推动者，希望彼此变好", ["growth_oriented", "achievement_need", "problem_solving_bond"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "pressure_defense_early_01",
    module: "pressure_defense",
    stage: "early",
    question: "当事情突然失控时，你更容易出现哪种反应？",
    options: [
      option("A", "短暂停下来，先恢复判断力", ["pause_to_regulate", "self_protective", "need_for_clarity"], ["inner_loop", "deep_needs"]),
      option("B", "立刻寻找可执行的补救方案", ["problem_solving", "decisive", "risk_aware"], ["behavior_action", "core_base"]),
      option("C", "反复回想是不是自己哪里没做好", ["self_blame", "self_demanding", "rumination"], ["inner_loop", "deep_needs"]),
      option("D", "表面保持稳定，之后才慢慢消化", ["stable_surface", "hidden_pressure", "delayed_processing"], ["relationship_pattern", "inner_loop"]),
    ],
  },
  {
    id: "pressure_defense_middle_02",
    module: "pressure_defense",
    stage: "middle",
    question: "压力变高时，你最明显的保护动作是什么？",
    options: [
      option("A", "减少表达，避免再增加变量", ["low_expression", "self_protective", "control_need"], ["relationship_pattern", "deep_needs"]),
      option("B", "把事情拆得更细，寻找可控点", ["needs_decomposition", "control_need", "practical_anchor"], ["behavior_action", "core_base"]),
      option("C", "对细节更敏感，也更容易被触动", ["sensitive", "detail_attuned", "emotion_aware"], ["relationship_pattern", "deep_needs"]),
      option("D", "更用力推进，直到看到确定结果", ["achievement_need", "self_pressure", "decisive"], ["inner_loop", "core_base"]),
    ],
  },
  {
    id: "pressure_defense_middle_03",
    module: "pressure_defense",
    stage: "middle",
    question: "你最容易被哪类压力消耗？",
    options: [
      option("A", "不确定性长期悬着", ["uncertainty_block", "stability_seeking", "need_for_clarity"], ["core_base", "inner_loop"]),
      option("B", "关系里的暗流和未说出口的话", ["emotion_aware", "low_guessing", "relationship_sensitive"], ["relationship_pattern", "deep_needs"]),
      option("C", "必须快速给答案，但我还没想清楚", ["cautious_decision", "low_pressure_support", "overthinking"], ["behavior_action", "deep_needs"]),
      option("D", "投入很多却看不到进展", ["achievement_need", "self_demanding", "frustration_with_stagnation"], ["core_base", "inner_loop"]),
    ],
  },
  {
    id: "pressure_defense_deep_04",
    module: "pressure_defense",
    stage: "deep",
    question: "压力状态下，别人怎样帮你更有效？",
    options: [
      option("A", "先把问题说清楚，不要急着安慰", ["needs_problem_framing", "clarity_need", "pragmatic"], ["behavior_action", "core_base"]),
      option("B", "给我一点空间，不要逼我马上回应", ["space_need", "low_pressure_support", "self_protective"], ["relationship_pattern", "deep_needs"]),
      option("C", "承认我的感受复杂，但不要放大焦虑", ["validation_need", "avoid_extra_anxiety", "sensitive"], ["deep_needs", "relationship_pattern"]),
      option("D", "帮我确定优先级，让事情重新可执行", ["priority_focus", "needs_next_step", "action_support"], ["behavior_action", "inner_loop"]),
    ],
  },
  {
    id: "pressure_defense_closing_05",
    module: "pressure_defense",
    stage: "closing",
    question: "当你从压力里恢复时，通常靠什么重新稳定？",
    options: [
      option("A", "靠重新获得清晰结构", ["clarity_need", "structured_action", "stability_seeking"], ["core_base", "behavior_action"]),
      option("B", "靠独处和降低外部刺激", ["space_need", "energy_sensitive", "self_protective"], ["deep_needs", "personality_structure"]),
      option("C", "靠确认关系没有破裂", ["validation_need", "relationship_sensitive", "trust_slow"], ["relationship_pattern", "deep_needs"]),
      option("D", "靠看到一个可衡量的进展", ["achievement_need", "practical_anchor", "growth_oriented"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "core_base_middle_01",
    module: "core_base",
    stage: "middle",
    question: "你内在最稳定的驱动力更接近哪一种？",
    options: [
      option("A", "把事情理解清楚，建立自己的判断", ["need_for_clarity", "internal_standard", "autonomous"], ["personality_structure", "behavior_action"]),
      option("B", "让生活和关系更可预测、更可靠", ["stability_seeking", "reliability_need", "control_need"], ["relationship_pattern", "deep_needs"]),
      option("C", "持续成长，不被原地困住", ["growth_oriented", "achievement_need", "future_driven"], ["behavior_action", "inner_loop"]),
      option("D", "保护真实感受，不被粗暴简化", ["authenticity_need", "sensitive", "self_protective"], ["relationship_pattern", "deep_needs"]),
    ],
  },
  {
    id: "core_base_deep_02",
    module: "core_base",
    stage: "deep",
    question: "你最希望自己长期拥有哪种能力？",
    options: [
      option("A", "在复杂局面里保持清醒判断", ["need_for_clarity", "risk_aware", "structured_action"], ["behavior_action", "pressure_defense"]),
      option("B", "在关系里既靠近也保有边界", ["boundary_need", "relationship_sensitive", "autonomy_need"], ["relationship_pattern", "deep_needs"]),
      option("C", "在压力下仍能稳定推进", ["resilient", "problem_solving", "practical_anchor"], ["pressure_defense", "behavior_action"]),
      option("D", "在成长中不被自我要求吞没", ["growth_oriented", "self_demanding", "self_compassion_need"], ["inner_loop", "deep_needs"]),
    ],
  },
  {
    id: "core_base_deep_03",
    module: "core_base",
    stage: "deep",
    question: "你判断一件事是否值得投入时，最在意什么？",
    options: [
      option("A", "它是否逻辑自洽、目标清楚", ["clarity_need", "value_check", "structured_action"], ["behavior_action", "inner_loop"]),
      option("B", "它是否会长期消耗我", ["low_drain", "energy_sensitive", "self_protective"], ["pressure_defense", "deep_needs"]),
      option("C", "它是否真的重要，而不是只是迎合别人", ["autonomy_need", "authenticity_need", "boundary_need"], ["relationship_pattern", "core_base"]),
      option("D", "它是否能带来成长或确定进展", ["growth_oriented", "achievement_need", "future_driven"], ["behavior_action", "inner_loop"]),
    ],
  },
  {
    id: "core_base_closing_04",
    module: "core_base",
    stage: "closing",
    question: "如果你的底层需求被满足，你会更像什么状态？",
    options: [
      option("A", "清醒、稳定、有自己的节奏", ["stability_seeking", "autonomous", "need_for_clarity"], ["deep_needs", "behavior_action"]),
      option("B", "柔和、开放，但边界仍然清楚", ["boundary_need", "validation_need", "authenticity_need"], ["relationship_pattern", "deep_needs"]),
      option("C", "专注、持续，不再被反复内耗拉回", ["deep_focus", "low_drain", "resilient"], ["inner_loop", "pressure_defense"]),
      option("D", "有目标、有推进感，也能允许自己停顿", ["growth_oriented", "self_compassion_need", "balanced_drive"], ["inner_loop", "pressure_defense"]),
    ],
  },
  {
    id: "inner_loop_middle_01",
    module: "inner_loop",
    stage: "middle",
    question: "你最常见的内耗循环从哪里开始？",
    options: [
      option("A", "想确认最优解，结果迟迟不敢落地", ["overthinking", "perfectionism", "uncertainty_block"], ["behavior_action", "pressure_defense"]),
      option("B", "察觉到别人的变化，开始反复解读", ["sensitive", "rumination", "relationship_sensitive"], ["relationship_pattern", "deep_needs"]),
      option("C", "明明累了，却觉得自己还不够好", ["self_demanding", "self_pressure", "self_blame"], ["pressure_defense", "deep_needs"]),
      option("D", "想说清楚，但又担心说了更复杂", ["fear_misread", "cautious_expression", "low_expression"], ["relationship_pattern", "pressure_defense"]),
    ],
  },
  {
    id: "inner_loop_deep_02",
    module: "inner_loop",
    stage: "deep",
    question: "当你开始反复思考时，最需要被区分的是什么？",
    options: [
      option("A", "现实风险和我脑内放大的风险", ["risk_aware", "avoid_extra_anxiety", "needs_problem_framing"], ["behavior_action", "pressure_defense"]),
      option("B", "对方真实表达和我的推测", ["low_guessing", "fear_misread", "relationship_sensitive"], ["relationship_pattern", "deep_needs"]),
      option("C", "我该负责的部分和不该背的部分", ["boundary_need", "self_blame", "responsibility_aware"], ["core_base", "relationship_pattern"]),
      option("D", "必须完成的事和只是想做到完美的事", ["perfectionism", "time_boundary_need", "self_demanding"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "inner_loop_deep_03",
    module: "inner_loop",
    stage: "deep",
    question: "哪种提醒最容易让你从内耗里出来？",
    options: [
      option("A", "先做一个足够小的验证，不需要一次想完", ["needs_next_step", "iterative_action", "low_entry_barrier"], ["behavior_action", "deep_needs"]),
      option("B", "把事实、感受、猜测分开写清楚", ["needs_problem_framing", "emotion_aware", "clarity_need"], ["pressure_defense", "relationship_pattern"]),
      option("C", "这件事不全是你的责任", ["self_blame", "boundary_need", "self_compassion_need"], ["relationship_pattern", "deep_needs"]),
      option("D", "先交付版本，再决定是否继续优化", ["perfectionism", "priority_focus", "time_boundary_need"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "inner_loop_closing_04",
    module: "inner_loop",
    stage: "closing",
    question: "如果要减少内耗，你最需要练习什么？",
    options: [
      option("A", "允许信息不完整时也先做小判断", ["uncertainty_tolerance", "cautious_decision", "needs_next_step"], ["behavior_action", "deep_needs"]),
      option("B", "不要把所有情绪变化都归因到自己", ["self_blame", "relationship_sensitive", "boundary_need"], ["relationship_pattern", "pressure_defense"]),
      option("C", "把休息视为重组，而不是退步", ["space_need", "self_compassion_need", "energy_sensitive"], ["pressure_defense", "deep_needs"]),
      option("D", "降低非核心事务的完成标准", ["perfectionism", "time_boundary_need", "low_drain"], ["behavior_action", "core_base"]),
    ],
  },
  {
    id: "deep_needs_deep_01",
    module: "deep_needs",
    stage: "deep",
    question: "什么状态会让你更有安全感？",
    options: [
      option("A", "环境可预测，节奏可掌控", ["stability_seeking", "control_need", "need_for_clarity"], ["core_base", "pressure_defense"]),
      option("B", "身边有人能稳定地支持你", ["validation_need", "reliability_need", "trust_slow"], ["relationship_pattern", "pressure_defense"]),
      option("C", "自己持续变强，有更多选择权", ["growth_oriented", "autonomy_need", "future_driven"], ["core_base", "behavior_action"]),
      option("D", "问题被说清楚，不再模糊悬着", ["clarity_need", "low_guessing", "stability_seeking"], ["relationship_pattern", "inner_loop"]),
    ],
  },
  {
    id: "deep_needs_deep_02",
    module: "deep_needs",
    stage: "deep",
    question: "你最不希望别人忽略你的哪一部分？",
    options: [
      option("A", "我不是不行动，只是需要先想清楚", ["cautious_decision", "need_for_clarity", "fear_misread"], ["behavior_action", "relationship_pattern"]),
      option("B", "我不是矫情，只是确实感受很细", ["sensitive", "validation_need", "emotion_aware"], ["relationship_pattern", "pressure_defense"]),
      option("C", "我不是没事，只是不习惯把压力摊开", ["self_contained", "hidden_pressure", "low_expression"], ["pressure_defense", "inner_loop"]),
      option("D", "我不是冷硬，只是对结果和成长很在意", ["growth_oriented", "self_demanding", "achievement_need"], ["core_base", "behavior_action"]),
    ],
  },
  {
    id: "deep_needs_closing_03",
    module: "deep_needs",
    stage: "closing",
    question: "如果让 AI 助手更懂你，你最希望它注意什么？",
    options: [
      option("A", "先帮我厘清问题，再给行动建议", ["needs_problem_framing", "clarity_need", "action_support"], ["behavior_action", "core_base"]),
      option("B", "少一点空泛鼓励，多一点具体路径", ["pragmatic", "needs_next_step", "avoid_empty_comfort"], ["behavior_action", "pressure_defense"]),
      option("C", "不要急着贴标签，保留复杂性", ["avoid_labeling", "authenticity_need", "fear_misread"], ["relationship_pattern", "core_base"]),
      option("D", "提醒风险，但不要制造额外焦虑", ["risk_aware", "avoid_extra_anxiety", "low_pressure_support"], ["pressure_defense", "inner_loop"]),
    ],
  },
];

export const firstQuestion = questionBank[0];

export const moduleMinimums: Record<Exclude<QuestionModule, "overall">, number> = {
  personality_structure: 2,
  behavior_action: 2,
  relationship_pattern: 2,
  pressure_defense: 2,
  core_base: 1,
  inner_loop: 1,
  deep_needs: 1,
};
